plugins:
  cppcheck:
    enabled: true
  cpplint:
    enabled: true
    config:
      filter: "-,+whitespace,+readability,-whitespace/ending_newline,-readability/multiline_string,-readability/casting"